// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl8PVXXXDVYtRGO1X3g8NrklMkkEn0eoQ',
    appId: '1:376940900754:web:06ee0bce312956fb83514b',
    messagingSenderId: '376940900754',
    projectId: 'flutter-chat-ceba1',
    authDomain: 'flutter-chat-ceba1.firebaseapp.com',
    storageBucket: 'flutter-chat-ceba1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChYY9vAIoVCg_qRmrTGhEufddUG2jfdlM',
    appId: '1:376940900754:android:d6b6742ca6e4c1de83514b',
    messagingSenderId: '376940900754',
    projectId: 'flutter-chat-ceba1',
    storageBucket: 'flutter-chat-ceba1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOtwTG-bXa06TtUoJWtjb0l99aaXsaWkM',
    appId: '1:376940900754:ios:26aa3c6f4f3733d183514b',
    messagingSenderId: '376940900754',
    projectId: 'flutter-chat-ceba1',
    storageBucket: 'flutter-chat-ceba1.appspot.com',
    iosClientId: '376940900754-vc0iu55t1locenmujfchvle3i2g9jfnl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOtwTG-bXa06TtUoJWtjb0l99aaXsaWkM',
    appId: '1:376940900754:ios:26aa3c6f4f3733d183514b',
    messagingSenderId: '376940900754',
    projectId: 'flutter-chat-ceba1',
    storageBucket: 'flutter-chat-ceba1.appspot.com',
    iosClientId: '376940900754-vc0iu55t1locenmujfchvle3i2g9jfnl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat.flutterChat',
  );
}
